[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_KEY = import.meta.env.VITE_API_KEY
  VITE_AUTH_DOMAIN = import.meta.env.VITE_AUTH_DOMAIN
  VITE_PROJECT_ID = import.meta.env.VITE_PROJECT_ID
  VITE_STORAGE_BUCKET = import.meta.env.VITE_STORAGE_BUCKET
  VITE_MESSAGING_SENDER_ID = import.meta.env.VITE_MESSAGING_SENDER_ID
  VITE_APP_ID = import.meta.env.VITE_APP_ID

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://*.cloudfunctions.net https://*.gstatic.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.google.com https://firebasestorage.googleapis.com https://*.googleusercontent.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; frame-src 'self' https://*.youtube.com https://*.firebaseapp.com"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()" 